##########################################

#
from PyQt5 import QtCore, QtGui, QtWidgets





######################################
class FirstGUI(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(1009, 412)
        self.CentralWidget = QtWidgets.QWidget(self)
        self.CentralWidget.setObjectName("CentralWidget")
        self.ProgramLabel = QtWidgets.QLabel(self.CentralWidget)
        self.ProgramLabel.setGeometry(QtCore.QRect(20, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ProgramLabel.setFont(font)
        self.ProgramLabel.setObjectName("ProgramLabel")
        self.InputATextEdit = QtWidgets.QPlainTextEdit(self.CentralWidget)
        self.InputATextEdit.setGeometry(QtCore.QRect(20, 120, 321, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InputATextEdit.setFont(font)
        self.InputATextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.InputATextEdit.setObjectName("InputATextEdit")
        self.Line = QtWidgets.QFrame(self.CentralWidget)
        self.Line.setGeometry(QtCore.QRect(20, 50, 971, 20))
        self.Line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line.setObjectName("Line")
        self.InputALabel = QtWidgets.QLabel(self.CentralWidget)
        self.InputALabel.setGeometry(QtCore.QRect(20, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputALabel.setFont(font)
        self.InputALabel.setObjectName("InputALabel")
        self.InputBTextEdit = QtWidgets.QPlainTextEdit(self.CentralWidget)
        self.InputBTextEdit.setGeometry(QtCore.QRect(370, 120, 321, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InputBTextEdit.setFont(font)
        self.InputBTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.InputBTextEdit.setObjectName("InputBTextEdit")
        self.InputBLabel = QtWidgets.QLabel(self.CentralWidget)
        self.InputBLabel.setGeometry(QtCore.QRect(370, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputBLabel.setFont(font)
        self.InputBLabel.setObjectName("InputBLabel")
        self.AlgorithmGroupBox = QtWidgets.QGroupBox(self.CentralWidget)
        self.AlgorithmGroupBox.setGeometry(QtCore.QRect(710, 110, 281, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AlgorithmGroupBox.setFont(font)
        self.AlgorithmGroupBox.setObjectName("AlgorithmGroupBox")
        self.legacyAlgoRadioButton = QtWidgets.QRadioButton(self.AlgorithmGroupBox)
        self.legacyAlgoRadioButton.setGeometry(QtCore.QRect(10, 110, 251, 41))
        self.legacyAlgoRadioButton.setObjectName("legacyAlgoRadioButton")
        self.StadardAlgoRadioButton = QtWidgets.QRadioButton(self.AlgorithmGroupBox)
        self.StadardAlgoRadioButton.setGeometry(QtCore.QRect(10, 60, 171, 31))
        self.StadardAlgoRadioButton.setChecked(True)
        self.StadardAlgoRadioButton.setObjectName("StadardAlgoRadioButton")
        self.AnalyzeButton = QtWidgets.QPushButton(self.AlgorithmGroupBox)
        self.AnalyzeButton.setEnabled(False)
        self.AnalyzeButton.setGeometry(QtCore.QRect(10, 167, 261, 51))
        self.AnalyzeButton.setObjectName("AnalyzeButton")
        self.InputBTextEdit.raise_()
        self.ProgramLabel.raise_()
        self.InputATextEdit.raise_()
        self.Line.raise_()
        self.InputALabel.raise_()
        self.InputBLabel.raise_()
        self.AlgorithmGroupBox.raise_()
        self.setCentralWidget(self.CentralWidget)
        self.StatusBar = QtWidgets.QStatusBar(self)
        self.StatusBar.setObjectName("StatusBar")
        self.setStatusBar(self.StatusBar)
        self.MenuBar = QtWidgets.QMenuBar(self)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 1009, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MenuBar.setFont(font)
        self.MenuBar.setObjectName("MenuBar")
        self.InfoRibbonButton = QtWidgets.QMenu(self.MenuBar)
        self.InfoRibbonButton.setObjectName("InfoRibbonButton")
        self.menuHelp = QtWidgets.QMenu(self.MenuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.setMenuBar(self.MenuBar)
        self.actionHelp = QtWidgets.QAction(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionHelp.setFont(font)
        self.actionHelp.setObjectName("actionHelp")
        self.actionGitHub = QtWidgets.QAction(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionGitHub.setFont(font)
        self.actionGitHub.setObjectName("actionGitHub")
        self.actionDocumentation = QtWidgets.QAction(self)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionHelp_2 = QtWidgets.QAction(self)
        self.actionHelp_2.setObjectName("actionHelp_2")
        self.actionGithubPage = QtWidgets.QAction(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionGithubPage.setFont(font)
        self.actionGithubPage.setObjectName("actionGithubPage")
        self.actionProgramVersion = QtWidgets.QAction(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionProgramVersion.setFont(font)
        self.actionProgramVersion.setObjectName("actionProgramVersion")
        self.actionDocumentation_2 = QtWidgets.QAction(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionDocumentation_2.setFont(font)
        self.actionDocumentation_2.setObjectName("actionDocumentation_2")
        self.InfoRibbonButton.addAction(self.actionGithubPage)
        self.InfoRibbonButton.addAction(self.actionProgramVersion)
        self.menuHelp.addAction(self.actionDocumentation_2)
        self.MenuBar.addAction(self.InfoRibbonButton.menuAction())
        self.MenuBar.addAction(self.menuHelp.menuAction())
        # ACTION LISTENERS
            # ribbon
        self.actionHelp.triggered.connect(self.updateAnalyzeButton)
        self.actionGitHub.triggered.connect(self.updateAnalyzeButton)
            # main page
        self.InputATextEdit.textChanged.connect(self.updateAnalyzeButton)
        self.InputBTextEdit.textChanged.connect(self.updateAnalyzeButton)
        self.legacyAlgoRadioButton.toggled.connect(self.updateAnalyzeButton)
        self.StadardAlgoRadioButton.toggled.connect(self.updateAnalyzeButton)
        self.AnalyzeButton.clicked.connect(self.analyzeInputs)
        # END OF ACTION LISTENERS
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CodeCheck 2.0"))
        self.ProgramLabel.setText(_translate("MainWindow", "CodeCheck 2.0"))
        self.InputALabel.setText(_translate("MainWindow", "Input A:"))
        self.InputBLabel.setText(_translate("MainWindow", "Input B:"))
        self.AlgorithmGroupBox.setTitle(_translate("MainWindow", "Algorithm Options:"))
        self.legacyAlgoRadioButton.setText(_translate("MainWindow", "CodeCheck 1.0 (Legacy)"))
        self.StadardAlgoRadioButton.setText(_translate("MainWindow", "CodeCheck 2.0"))
        self.AnalyzeButton.setText(_translate("MainWindow", "Analyze"))
        self.InfoRibbonButton.setTitle(_translate("MainWindow", "Info"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHelp.setText(_translate("MainWindow", "Version"))
        self.actionGitHub.setText(_translate("MainWindow", "GitHub"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionHelp_2.setText(_translate("MainWindow", "Help"))
        self.actionGithubPage.setText(_translate("MainWindow", "Github Page"))
        self.actionProgramVersion.setText(_translate("MainWindow", "Version"))
        self.actionDocumentation_2.setText(_translate("MainWindow", "Documentation"))

    def analyzeInputs(self):
        print("InputA: ",self.InputATextEdit.toPlainText())
        print("InputB: ",self.InputBTextEdit.toPlainText())
        if(self.legacyAlgoRadioButton.isChecked()):
            print("Algorithm: ","CodeCheck Legacy")
        if(self.StadardAlgoRadioButton.isChecked()):
            print("Algorithm: ","CodeCheck 2.0")


        # new second GUI
        self.open_second_window()

    # action listener endpoint to process UX "analyze" button
    def updateAnalyzeButton(self):
        if(self.InputATextEdit.toPlainText() and self.InputBTextEdit.toPlainText() and
           (self.legacyAlgoRadioButton.isChecked() or
           self.StadardAlgoRadioButton.isChecked())):
            self.AnalyzeButton.setEnabled(True)
        else:    
            self.AnalyzeButton.setEnabled(False)

    def open_second_window(self):
        # create instance of SecondGUI class
        self.second_window = SecondGUI()
        # close first window
        self.close()
        # show second window
        self.second_window.show()

######################################
class SecondGUI(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        self.setObjectName("MainWindow")
        self.resize(575, 717)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.GeneralBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.GeneralBrowser.setGeometry(QtCore.QRect(20, 110, 531, 111))
        self.GeneralBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GeneralBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GeneralBrowser.setObjectName("GeneralBrowser")
        self.InputABrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.InputABrowser.setGeometry(QtCore.QRect(20, 300, 531, 131))
        self.InputABrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.InputABrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.InputABrowser.setObjectName("InputABrowser")
        self.InputBBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.InputBBrowser.setGeometry(QtCore.QRect(20, 470, 531, 131))
        self.InputBBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.InputBBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.InputBBrowser.setObjectName("InputBBrowser")
        self.GeneralLabel = QtWidgets.QLabel(self.centralwidget)
        self.GeneralLabel.setGeometry(QtCore.QRect(20, 70, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GeneralLabel.setFont(font)
        self.GeneralLabel.setObjectName("GeneralLabel")
        self.InputALabel = QtWidgets.QLabel(self.centralwidget)
        self.InputALabel.setGeometry(QtCore.QRect(20, 260, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputALabel.setFont(font)
        self.InputALabel.setObjectName("InputALabel")
        self.InputBLabel = QtWidgets.QLabel(self.centralwidget)
        self.InputBLabel.setGeometry(QtCore.QRect(20, 430, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputBLabel.setFont(font)
        self.InputBLabel.setObjectName("InputBLabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 50, 531, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ProgramLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProgramLabel.setGeometry(QtCore.QRect(20, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ProgramLabel.setFont(font)
        self.ProgramLabel.setObjectName("ProgramLabel")
        self.CloseProgramButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseProgramButton.setGeometry(QtCore.QRect(20, 630, 531, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CloseProgramButton.setFont(font)
        self.CloseProgramButton.setObjectName("CloseProgramButton")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionSave_Results_as_HTML = QtWidgets.QAction(self)
        self.actionSave_Results_as_HTML.setObjectName("actionSave_Results_as_HTML")
        self.actionSave_as = QtWidgets.QAction(self)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_as_2 = QtWidgets.QAction(self)
        self.actionSave_as_2.setObjectName("actionSave_as_2")
        self.menuFile.addAction(self.actionSave_Results_as_HTML)
        self.menuFile.addAction(self.actionSave_as_2)
        self.menubar.addAction(self.menuFile.menuAction())
        # ACTION LISTENERS
        self.CloseProgramButton.clicked.connect(self.close)
        # END OF ACTION LISTENERS
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CodeCheck 2.0 Result"))
        self.GeneralBrowser.setHtml(_translate("MainWindow", "<h3>this works?</h3>"))
        self.InputABrowser.setHtml(_translate("MainWindow", "<h2>Input A works?</h2>"))
        self.InputBBrowser.setHtml(_translate("MainWindow", "<h1>Input B works?</h3>"))
        self.GeneralLabel.setText(_translate("MainWindow", "General Analysis:"))
        self.InputALabel.setText(_translate("MainWindow", "Input A:"))
        self.InputBLabel.setText(_translate("MainWindow", "Input B:"))
        self.ProgramLabel.setText(_translate("MainWindow", "CodeCheck Results:"))
        self.CloseProgramButton.setText(_translate("MainWindow", "Close Program"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_Results_as_HTML.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as_2.setText(_translate("MainWindow", "Save as"))

    def closeProgram(self):
        self.close()
######################################

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = FirstGUI()
    window.show()
    sys.exit(app.exec_())
