# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Austin/AppData/Local/Temp/CodeCheck2 ResultsyPiisl.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow




# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Austin/AppData/Local/Temp/CodeCheck2 ResultsMoFhda.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultsWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GeneralBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.GeneralBrowser.setGeometry(QtCore.QRect(20, 110, 531, 111))
        self.GeneralBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GeneralBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GeneralBrowser.setObjectName("GeneralBrowser")
        self.InputABrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.InputABrowser.setGeometry(QtCore.QRect(20, 300, 531, 131))
        self.InputABrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.InputABrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.InputABrowser.setObjectName("InputABrowser")
        self.InputBBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.InputBBrowser.setGeometry(QtCore.QRect(20, 470, 531, 131))
        self.InputBBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.InputBBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.InputBBrowser.setObjectName("InputBBrowser")
        self.GeneralLabel = QtWidgets.QLabel(self.centralwidget)
        self.GeneralLabel.setGeometry(QtCore.QRect(20, 70, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GeneralLabel.setFont(font)
        self.GeneralLabel.setObjectName("GeneralLabel")
        self.InputALabel = QtWidgets.QLabel(self.centralwidget)
        self.InputALabel.setGeometry(QtCore.QRect(20, 260, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputALabel.setFont(font)
        self.InputALabel.setObjectName("InputALabel")
        self.InputBLabel = QtWidgets.QLabel(self.centralwidget)
        self.InputBLabel.setGeometry(QtCore.QRect(20, 430, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputBLabel.setFont(font)
        self.InputBLabel.setObjectName("InputBLabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 50, 531, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ProgramLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProgramLabel.setGeometry(QtCore.QRect(20, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ProgramLabel.setFont(font)
        self.ProgramLabel.setObjectName("ProgramLabel")
        self.CloseProgramButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseProgramButton.setGeometry(QtCore.QRect(20, 630, 531, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CloseProgramButton.setFont(font)
        self.CloseProgramButton.setObjectName("CloseProgramButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Results_as_HTML = QtWidgets.QAction(MainWindow)
        self.actionSave_Results_as_HTML.setObjectName("actionSave_Results_as_HTML")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_as_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_as_2.setObjectName("actionSave_as_2")
        self.menuFile.addAction(self.actionSave_Results_as_HTML)
        self.menuFile.addAction(self.actionSave_as_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CodeCheck 2.0 Result"))
        self.GeneralBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">general</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.InputABrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Input A </span></p></body></html>"))
        self.InputBBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Input B </span></p></body></html>"))
        self.GeneralLabel.setText(_translate("MainWindow", "General Analysis:"))
        self.InputALabel.setText(_translate("MainWindow", "Input A:"))
        self.InputBLabel.setText(_translate("MainWindow", "Input B:"))
        self.ProgramLabel.setText(_translate("MainWindow", "CodeCheck Results:"))
        self.CloseProgramButton.setText(_translate("MainWindow", "Close Program"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_Results_as_HTML.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as_2.setText(_translate("MainWindow", "Save as"))


app = QtWidgets.QApplication(sys.argv)
ui = Ui_ResultsWindow()
MainWindow = QMainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())

